### ISSUE TITLE
Color scheme

### ISSUE THREAD

**Issue by gsantner** [codeasashu/hcz-jekyll-blog#11]
Hi there,
 I just found your great theme, but I couln't find an easy way to change the color scheme.  
I looked at the sass and css files, but there seems to be no central option to control the primary and secondary colors (actually teal).

It would be great if the theme allows setting these colors without modifing the minified css files.
Please add an configurable option.

**Comment by ashutosh2k12** [comment]
Yes, I have not included color variables in SASS as of now since I just hardcoded it initially and went on with it due to lack of time. I will be adding colors in SCSS as well as config file color variables to address the issue. Thanks for using the theme

**Comment by GreatEmerald** [comment]
Regenerating the bootstrap-material-design CSS files using a different colour isn't that difficult, though. One can just follow this guide for now: https://spapas.github.io/2014/12/16/change-bootstrap-material-primary-color/

**Comment by ashutosh2k12** [comment]
@GreatEmerald that was not what I was referring to. However, glad you posted the links. Some colors like the top header and side menu colors are my custom hex which are hardcoded for now. I wanted them to change via variables. However, I will soon make a custom color setting for whole bootstrap colors alltogether. Thanks for the comment
